version: "3.8"

services:
  api1:
    build: ./api1
    ports:
      - "8000:8000"
    volumes:
      - ./api1:/app # Mount โค้ดจากเครื่องเราเข้า container
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - api2

  api2:
    build: ./api2
    ports:
      - "8001:8001"
    volumes:
      - ./api2:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8001 --reload
